polyphony-chat/chorus

- src/api/auth/login.rs
- src/api/schemas.rs
This PR adds login functionality! The branch can therefore be deleted upon merging.
> Implement Login, close feature branch

- src/api/types.rs
Another merge from rest-of-discord-types
> Add session, guild event types

- src/api/auth/login.rs
- src/api/auth/register.rs
- src/api/channels/messages.rs
- src/api/guilds/guilds.rs
- src/api/policies/instance/instance.rs
- src/api/types.rs
- src/api/users/users.rs
- src/instance.rs
Replace &mut Instance with Rc<RefCell<Instance>> on the User struct to represent the 1:n relation of Instance:User
> Replace &mut Instance with Rc<RefCell<Instance>>

- src/api/policies/instance/limits.rs
- src/api/schemas.rs
- src/errors.rs
- src/gateway.rs
- tests/integration.rs
This pull request fixes a few typos, no functional changes intended.
> Fix some typos

- README.md
- src/api/guilds/roles.rs
- src/types/schema/role.rs
- tests/roles.rs
This PR implements all relevant routes for /roles/. Some things do not yet have integration tests but pshhhhhhhh i will add them later
> Implement Role Management

- src/api/auth/register.rs
- src/api/channels/channels.rs
- src/api/channels/messages.rs
- src/api/channels/permissions.rs
- src/api/channels/reactions.rs
- src/api/common.rs
- src/api/guilds/guilds.rs
- src/api/guilds/member.rs
- src/api/guilds/roles.rs
- src/api/users/relationships.rs
- src/api/users/users.rs
> Fix clippy::await_holding_refcell_ref false positives

- src/api/channels/channels.rs
- src/api/channels/permissions.rs
- src/api/channels/reactions.rs
- src/api/common.rs
- src/api/guilds/guilds.rs
- src/api/guilds/member.rs
- src/api/users/relationships.rs
- src/api/users/users.rs
- tests/channel.rs
- tests/guild.rs
Should perform the change in #116
> Change Option<ChorusLibError> to Result<(), ChorusLibError>

- examples/gateway_observers.rs
- src/gateway.rs
- src/types/events/resume.rs
- tests/message.rs
- allow multiple observers
- Merged `update_data` & `notify`
- removed interior mutability
> Simplify GatewayEvent

- src/api/channels/channels.rs
- src/types/schema/channel.rs
- tests/channel.rs
- tests/message.rs
Implement [Get Channel Messages](https://discord.com/developers/docs/resources/channel#get-channel-messages).
my first PR that actually adds more lines than it removes :3
> Get channel messages

- src/api/channels/reactions.rs
- tests/common/mod.rs
Previously, the above mentioned function didn't return anything on success, even though it should have. This PR fixes that.
> Make ReactionMeta::get() return a Vec<PublicUser>

- Cargo.toml
> Correct tokio features

- Cargo.toml
- examples/gateway_observers.rs
- src/gateway.rs
Simple change that adds async-trait to the Observer trait.
> Async Observer Trait

- Cargo.lock
- Cargo.toml
Bumps the versions of all crates which had an update.
> Bump crate versions

- src/api/channels/messages.rs
- tests/channels.rs
- tests/messages.rs
Closes #138 by applying the fixes suggested in the issue. Thanks for reporting, @SpecificProtagonist! :)
> Fix: message file attachment duplication

- src/types/entities/message.rs
> Changed struct reaction

- src/api/channels/channels.rs
- src/api/channels/messages.rs
- src/api/channels/permissions.rs
- src/api/channels/reactions.rs
- src/api/guilds/guilds.rs
- src/api/guilds/member.rs
- src/api/guilds/roles.rs
- src/api/invites/mod.rs
- src/api/users/channels.rs
- src/api/users/guilds.rs
- src/api/users/relationships.rs
- src/api/users/users.rs
> Change bearer_auth to header("Authorization"

- src/types/entities/channel.rs
> Change type of Channel::last_pin_timestamp

- src/api/channels/channels.rs
- src/types/schema/channel.rs
> Modify Guild Channel Positions

- src/api/channels/messages.rs
- src/types/entities/message.rs
- tests/messages.rs
Implements the above mentioned features, including a basic test
Closes #268, #269, #270
> Get pinned, pin, unpin Message

- src/api/channels/messages.rs
> Add message: get

- src/api/channels/messages.rs
- src/types/entities/attachment.rs
- src/types/entities/emoji.rs
- src/types/entities/message.rs
- src/types/schema/message.rs
More message routes!
Closes #260, #263, #264, #256, #407, #265, #266, #267
> Message routes

- src/api/guilds/guilds.rs
- src/api/users/guilds.rs
- src/lib.rs
- src/types/entities/sticker.rs
- src/types/schema/guild.rs
Merging this adds some new Guild routes, and also checks some boxes in the Guild Meta Issue.
> Guild routes

- Cargo.toml
- src/api/auth/login.rs
- src/api/auth/register.rs
- src/api/channels/channels.rs
- src/api/channels/messages.rs
- src/api/channels/permissions.rs
- src/api/channels/reactions.rs
- src/api/guilds/guilds.rs
- src/api/guilds/member.rs
- src/api/guilds/roles.rs
- src/api/invites/mod.rs
- src/api/users/channels.rs
- src/api/users/guilds.rs
- src/api/users/relationships.rs
- src/api/users/users.rs
- src/instance.rs
- src/ratelimiter.rs
Replace `belongs_to: Rc<RefCell<Instance>>` with `Arc<RwLock<Instance>>` to make `ChorusUser` `Send`
> Make `ChorusUser` `Send`

- .github/workflows/build_and_test.yml
- .github/workflows/rust-clippy.yml
- bump checkout to @v4
- bump rust-toolchain to @v1
> bump actions version

- src/instance.rs
- src/lib.rs
- src/types/config/types/general_configuration.rs
- src/types/config/types/subconfigs/limits/ratelimits/auth.rs
- src/types/config/types/subconfigs/limits/ratelimits/mod.rs
- src/types/config/types/subconfigs/limits/ratelimits/route.rs
- src/types/config/types/subconfigs/limits/rates.rs
- src/types/entities/ratelimits.rs
- tests/auth.rs
Add some sensible implementations for PartialEq, Eq, etc. where I found them to be necessary
> More derives and impls

- src/instance.rs
- make `Instance::from_url_bundle` pub, update some `Instance` docs, move `Instance::clone_limits_if_some` so it isn't in between two pub functions
> Minor instance updates

- examples/gateway_simple.rs
- src/gateway/handle.rs
- src/gateway/heartbeat.rs
- src/gateway/mod.rs
- src/types/entities/mod.rs
- tests/common/mod.rs
- tests/gateway.rs
This PR slightly improves the ergonomics of working with self-updating structs, by making the changes as documented in #466.
> "Self updating structs" API improvements

- README.md
- examples/login.rs
- src/errors.rs
- src/gateway/handle.rs
- src/gateway/heartbeat.rs
- src/gateway/message.rs
- src/instance.rs
- src/lib.rs
- src/types/events/lazy_request.rs
- src/types/events/message.rs
- tests/common/mod.rs
This pull request fixes a few typos, no functional changes intended.
> Fix a few typos

- src/api/guilds/guilds.rs
- src/api/users/channels.rs
- src/types/schema/guild.rs
Add #156, update some docs a bit, reorder some methods for readability
> Minor docs updates, add Get Private Channels

- Cargo.lock
[RUSTSEC-2024-0020](https://rustsec.org/advisories/RUSTSEC-2024-0020.html)
> Bump whoami to fix stack buffer overflow

- src/types/entities/channel.rs
- src/types/entities/role.rs
- src/types/entities/webhook.rs
- src/types/events/voice_gateway/speaking.rs
- src/types/schema/channel.rs
- tests/channels.rs
This should bring chorus up to speed with the channels api in regards to spacebar's current implementation.
> Update and add some types in support of the backend

- examples/login.rs
- src/api/auth/login.rs
- src/api/auth/mod.rs
- src/api/auth/register.rs
- src/api/channels/channels.rs
- src/api/channels/messages.rs
- src/api/channels/permissions.rs
- src/api/channels/reactions.rs
- src/api/guilds/guilds.rs
- src/api/guilds/roles.rs
- src/errors.rs
- src/instance.rs
- src/ratelimiter.rs
- src/types/entities/mfa_token.rs
- src/types/entities/mod.rs
- src/types/schema/auth.rs
- src/types/schema/mfa.rs
- src/types/schema/mod.rs
- tests/auth.rs
- tests/channels.rs
- tests/common/mod.rs
- tests/guilds.rs
- tests/members.rs
- tests/messages.rs
- tests/relationships.rs
Here is my suggested implementation of MFA #40 
- Adds the required Request/Response structs for the MFA implementation.
- Adds a new MfaRequired error on `ChorusError`.
- Adds `complete_mfa_challenge` which calls the endpoint to verify MFA.
- Removes struct `TotpSchema`.
- Changes ChorusUser struct definition, the `user` field type is wrapped with `Option` so there is an exact way to know when it is authenticated. The `shell` function has also been changed accordingly.
- Changes current API endpoints according to the changes made to ChorusUser.
- The following changes are a foundation for a future full MFA implementation throughout all endpoints that require it, as some endpoints are not implemented yet.
- For unauthenticated endpoints that require MFA verification, a user of the library …
> MFA implementation

- src/gateway/backends/tungstenite.rs
When connecting to a Gateway using the tungstenite backend, match, whether the supplied URL is of type "ws" or "wss" and choose the appropriate "connect" function in tungstenite. There is no need to construct a `RootCertStore` with loaded root trust certificates from disk, if we completely ignore this `RootCertStore` anyways.
> Tungstenite: Match scheme for "ws" or "wss"

- src/types/events/ready.rs
Updates/Extends the GatewayReady event to include all the missing fields.
> Ready Event Updates

- src/types/entities/user.rs
The fix I previously used to make our enum types compatible with PG does not work as expected. This is a better fix using custom en-/decoding rules.
> Implement custom sqlx::Postgres en-/decoding for PremiumType enum

- Cargo.lock
- Cargo.toml
- src/gateway/backends/tungstenite.rs
- src/gateway/message.rs
- src/voice/gateway/backends/tungstenite.rs
> Fix dependabot updating the wrong branch

- src/lib.rs
Fixes a bug? where `UrlBundle::from_root_url` would return a `UrlBundle` which had the api url as the root url, instead of the provided root url
also adds a few helper functions for `UrlBundle`
> fix: use provided root url in UrlBundle::from_root_url
