src/api/auth/login.rs, src/api/auth/register.rs, src/api/channels/channels.rs, src/api/channels/messages.rs, src/api/channels/permissions.rs, src/api/channels/reactions.rs, src/api/guilds/guilds.rs, src/api/guilds/member.rs, src/api/guilds/roles.rs, src/api/policies/instance/instance.rs, src/api/policies/instance/limits.rs, src/api/users/relationships.rs, src/api/users/users.rs, src/instance.rs, src/lib.rs, src/limit.rs, tests/common/mod.rs
The fields are public, so no getters necessary.
Also renamed `URLBundle` to `UrlBundle` to stay in line with the [rust api guidelines](https://rust-lang.github.io/api-guidelines/naming.html). Note that if getters were necessary, they recommend omitting the `get_` prefix.
=> UrlBundle remove getters

Cargo.toml, src/types/config/mod.rs, src/types/utils/mod.rs, src/types/utils/snowflake.rs
Also fixes bug where the non-atomic increment could lead to two threads generating the same snowflake twice.
Something I'm unsure about are the implications for sqlx. Snowflakes are 64-bit numbers, but sqlx previously got given a string representation. At the same time at least sqlite can automatically coerce the two. I'm not sure what the intentions are here.
=> Simplify Snowflake

src/api/channels/channels.rs, src/api/channels/messages.rs, src/api/channels/permissions.rs, src/api/channels/reactions.rs, src/gateway.rs, src/types/entities/audit_log.rs, src/types/entities/channel.rs, src/types/entities/guild.rs, src/types/entities/template.rs, src/types/events/call.rs, src/types/events/channel.rs, src/types/events/guild.rs, src/types/events/integration.rs, src/types/events/invite.rs, src/types/events/lazy_request.rs, src/types/events/message.rs, src/types/events/passive_update.rs, src/types/events/request_members.rs, src/types/events/thread.rs, src/types/events/voice.rs, src/types/events/webhooks.rs, src/types/interfaces/activity.rs, src/types/schema/channel.rs, tests/channel.rs, tests/message.rs
I've definitely missed some, but these should be most. Sadly the Spacebar api docs use the type `string` both for strings and for snowflakes.
=> More consistent use of snowflakes

src/api/channels/channels.rs, src/api/channels/reactions.rs, src/api/guilds/guilds.rs, src/api/guilds/member.rs, src/api/guilds/roles.rs, src/api/users/relationships.rs, src/types/entities/guild_member.rs, tests/channel.rs, tests/common/mod.rs, tests/guild.rs, tests/member.rs, tests/relationships.rs, tests/roles.rs
Covers function arguments missed by #122. This also lead to an elimination of a bunch of clone calls.
=> Always use Snowflakes in args

src/api/policies/instance/ratelimits.rs, src/instance.rs
Implementing serdes `Deserialize` and `Serialize` for `LimitsConfiguration` and its children types provides one with all the tools needed to store and load this information on disk. Remembering rate limits is important if you want to build things like a Client based on Chorus. Closes #34
=> Enable saving and loading LimitsConfiguration

src/api/auth/login.rs, src/api/auth/register.rs, src/api/users/users.rs, src/instance.rs, tests/common/mod.rs, tests/gateway.rs, tests/invites.rs
By adding `GatewayHandle` to `UserMeta` (which we should do anyways), the initalization code for the gateway connection can be moved there, which cleans up the usage of auto updating structs by deduplicating/removing boilerplate.
=> Improve auto updating structs usage

src/api/guilds/guilds.rs, src/types/schema/guild.rs, tests/guilds.rs
- Closes #299
- Add derives for `GuildCreateSchema`
- Add `GuildBanCreateSchema`
- Add `Guild::create_ban`
=> Create Guild Ban

tests/guilds.rs
By checking for an error on trying to ban the same person again, we can kind of gauge if the ban functionality actually works.
=> Make ban test a little more meaningful

Cargo.lock, Cargo.toml
It seems, as if the regular `sqlx` does everything that chorus needs atm. Therefore, we can switch to the official version of that lib.
=> replace sqlx-git-custom with sqlx

src/api/auth/login.rs, src/api/auth/register.rs, src/gateway.rs, src/instance.rs, tests/common/mod.rs
As `GatewayHandle` in itself is just a bundle of refrences, this pr makes it clonable and removes the `Arc` from `ChorusUser`.
=> Make GatewayHandle Clone and remove Arc

Cargo.lock, Cargo.toml, chorus-macros/Cargo.toml, chorus-macros/src/lib.rs, src/gateway.rs, src/instance.rs, src/types/entities/guild.rs, src/types/events/auto_moderation.rs, src/types/events/channel.rs, src/types/events/guild.rs, src/types/events/mod.rs, src/types/events/thread.rs
The changes in this branch include a ton of QoL improvements I have discovered while working on the Client, using Chorus.
=> Merge Dev changes into main

Cargo.lock, Cargo.toml, src/gateway.rs, src/types/config/types/security_configuration.rs
This PR removes the dependency on `openssl`, which is not compatible with the `wasm32-unknown-unknown` target, completely. It is replaced by `rustls` for TLS/SSL and `rand` for cryptographically safe pseudo-RNG.
=> Remove openssl, use rustls and rand instead

src/gateway/backend_tungstenite.rs, src/gateway/gateway.rs, src/gateway/handle.rs, src/gateway/heartbeat.rs, src/gateway/message.rs, src/gateway/mod.rs
Allow for swapping out the websockets backend depending on the platform.
=> Prepare for platform-dependant websockets backend

.cargo/config.toml, .github/workflows/build_and_test.yml, Cargo.lock, Cargo.toml, examples/gateway_observers.rs, examples/gateway_simple.rs, src/gateway/backend_tungstenite.rs, src/gateway/backends/mod.rs, src/gateway/backends/tungstenite.rs, src/gateway/backends/wasm.rs, src/gateway/gateway.rs, src/gateway/handle.rs, src/gateway/heartbeat.rs, src/gateway/mod.rs, tests/wasm.rs
This PR is adding
Combined coverage report uploading (treat wasm and regular test runs as one coverage report for coveralls.io) is sadly not possible yet, due to llvms profiler not supporting wasm
=> initial wasm32 'support'

examples/login.rs, src/api/auth/login.rs, src/api/auth/register.rs, tests/auth.rs
Register and login, for some reason, required ownership of the `Instance` object. This was not necessary and has been changed in this PR. The PR also includes some extra tests, like logging in, logging in with a token, etc.
=> Coverage, change register/login

Cargo.lock, Cargo.toml, examples/gateway_observers.rs, examples/gateway_simple.rs, src/gateway/heartbeat.rs, tests/gateway.rs
It turns out `std::time::Instant::now()` panics WASM (see #459) and breaks the heartbeat handler.
This pr attempts to fix that by replacing `std::time::Instant` with `wasmtimer::std::Instant` and `safina_timer::sleep_until` with `wasmtimer::tokio::sleep_until`.
=> Fix gateway heartbeat on WASM

.github/workflows/build_and_test.yml
This pull request updates [`actions/setup-node`](https://github.com/actions/setup-node) to v4.
Still using the older version of the action will generate warnings in CI runs, for example in https://github.com/polyphony-chat/chorus/actions/runs/7647051423:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The PR will get rid of those warnings.
=> Bump actions/setup-node in GHA workflow to v4

Cargo.lock
The update fixes a resource exhaustion vulnerability in `h2` which may lead to Denial of Service. For more information on that see <https://rustsec.org/advisories/RUSTSEC-2024-0003>.
=> Update h2 to 0.3.24 to fix vulnerability RUSTSEC-2024-0003

README.md
This pr fixes the example in the readme to work after the Instance api changes in #456
=> Fix example in readme for #456

.github/workflows/rust-clippy.yml
This replaces the [unmaintained](https://github.com/actions-rs/toolchain/issues/216) `actions-rs/toolchain` by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/polyphony-chat/chorus/actions/runs/7647051419:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/toolchain@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced …
=> Replace unmaintained actions-rs/toolchain by dtolnay/rust-toolchain

.github/workflows/rust-clippy.yml
https://github.com/github/codeql-action v2 is now deprecated, and the latest version is v3.
=> Update github/codeql-action to v3

CONTRIBUTING.md, README.md
Moves the contribution guidelines from README.md to CONTRIBUTING.md, as per @striezel's suggestion.
=> Move contribution guidelines to CONTRIBUTING.md

src/api/users/relationships.rs, src/api/users/users.rs, src/types/events/lazy_request.rs
At some point luna.gitlab.io updated their url structure and now all existing links return a 404. This pr updates the links in our documentation to properly point to the right new urls.
=> Fix broken luna.gitlab.io links

Cargo.lock
Bump mio in Cargo.lock to fix [RUSTSEC-2024-0019](https://rustsec.org/advisories/RUSTSEC-2024-0019.html)
=> Bump mio to fix RUSTSEC-2024-0019

src/types/entities/config.rs
- use the ? operator, as clippy suggested on #487
=> Fix code scanning alerts on #487

.github/workflows/build_and_test.yml
Sometimes wasm tests hang and run for several hours before being killed, 30 minutes should be more than enough to run all tests normally
=> Limit test actions to 30 minutes

chorus-macros/Cargo.lock, chorus-macros/Cargo.toml, chorus-macros/src/lib.rs
Added #486 and bumped version of chorus-macros, can't perform the change in chorus yet though, since macros needs to be published first
=> add WebSocketEvent macro derive, bump chorus-macros to 0.3.0

Cargo.lock, src/gateway/handle.rs, src/gateway/mod.rs, src/instance.rs, src/types/entities/application.rs, src/types/entities/audit_log.rs, src/types/entities/auto_moderation.rs, src/types/entities/channel.rs, src/types/entities/emoji.rs, src/types/entities/guild.rs, src/types/entities/guild_member.rs, src/types/entities/integration.rs, src/types/entities/invite.rs, src/types/entities/message.rs, src/types/entities/mod.rs, src/types/entities/relationship.rs, src/types/entities/sticker.rs, src/types/entities/team.rs, src/types/entities/template.rs, src/types/entities/user_settings.rs, src/types/entities/voice_state.rs, src/types/entities/webhook.rs, src/types/events/channel.rs, src/types/events/guild.rs, src/types/events/mod.rs, src/types/mod.rs, tests/common/mod.rs
This pr includes various fixes:
- bump rustls to 0.21.11, to fix an (although n/a to chorus) [security vulnerability](https://github.com/advisories/GHSA-6g7w-8wpp-frhj)
- bump h2 to 0.3.26 to fix another (although n/a to chorus) [security vulnerability](https://github.com/advisories/GHSA-q6cp-qfwq-4gcv)
- move type alias `Shared<T>` from `src/gateway/mod.rs` (feature locked behind `client`) to `src/types/mod.rs`, to fix compiler errors when building without the `client` feature:
```
error[E0432]: unresolved import `crate::gateway`
--> src/types/entities/mod.rs:30:12
|
30 | use crate::gateway::Shared;
|            ^^^^^^^ could not find `gateway` in the crate root
error[E0432]: unresolved import `crate::gateway`
--> src/types/entities/application.rs:10:12
|
10 | use crate::gateway::Shared; …
```
=> Move Shared<T> to types/mod.rs, bump some dependencies

src/errors.rs, src/gateway/backends/tungstenite.rs, src/gateway/backends/wasm.rs, src/gateway/gateway.rs, src/voice/gateway/backends/mod.rs, src/voice/gateway/backends/tungstenite.rs, src/voice/gateway/backends/wasm.rs, src/voice/gateway/gateway.rs, src/voice/gateway/handle.rs, src/voice/gateway/heartbeat.rs
When I first implemented the voice gateway, I (pretty foolishly) just copy-pasted the code for the regular gateway backends, with some type changes. Now I've thought of a pretty easy to way to have the websocket backends implemented in just one place, so they aren't duplicated. ([also because there is potentially another type of gateway to implement](https://docs.discord.sex/remote-authentication/intro), and maintaining the same code three times would be a pain)
=> Reuse gateway backends, don't duplicate them for voice gateway

.github/workflows/build_and_test.yml, Cargo.lock, semver_release_checks.yml
Changes:
- add an experimental check for semver compliance on pull requests to main (which are usually releases)
- 'fix' `wasm-gecko` by changing it to run on `ubuntu-latest`, since geckodriver no longer supports arm64 macos
- Cargo check a few common non-default feature configuration, sort of doing #497 (mostly so we don't give symfonia build errors)
- bump `wasm-bindgen` to `0.2.92`
=> Ci improvements

Cargo.lock, Cargo.toml, chorus-macros/Cargo.lock, chorus-macros/Cargo.toml
- Bumps chorus macros to 0.4.0, followup to #505
- Makes builds within the repo use the local path and published releases use a set version of the macros crate
=> Bump chorus macros to 0.4.0

src/types/entities/channel.rs
This simply add's a custom Deserialize impl for PermissionOverwriteType to allow deserialization from both ints and strings.
=> Add custom deserializer for PermissionOverwriteType

Cargo.lock, Cargo.toml, README.md, build-wasm.sh, src/gateway/backends/tungstenite.rs, test-wasm.sh
This PR removes the `openssl` dependency in favor of `rustls`. The benefits to doing this are:
- **Less `unsafe`**: `openssl` relies on the `openssl-sys` FFI crate, which wraps `unsafe` FFIs with no added soundness guarantees, afaik. `rustls` is written in Rust and provides no `unsafe` features by default.
- **No `openssl-sys`**: Linux, macOS and other UNIX-users have to install a dev-package for the openssl library in order to compile chorus. This PR changes that, improving portability
- **No openssl, in general**: OpenSSL has a long history of implementation defects. Naturally, removing the OpenSSL dependency in favor of a modern and safe replacement changes this.
Note, that with this PR, certificates are no longer provided by the system, but rather by the `webpki_roots` crate, which …
=> No openssl

.github/workflows/build_and_test.yml, CONTRIBUTING.md
This PR switches the `linux` job from `cargo test` to `cargo nextest run` for > 50% time reduction in the test execution step of the CI pipeline. Also, the "check common non default feature configurations" step has been moved from the `linux` job to it's own job, to parallelize the CI pipeline further and reduce the time that CI needs to run to completion.
=> Use cargo nextest

src/types/events/hello.rs
Replaces the derived `std::default::Default` with
```rs
impl std::default::Default for GatewayHello {
fn default() -> Self {
Self {
// "HELLO" opcode is 10
op: 10,
d: Default::default(),
}
}
}
impl std::default::Default for HelloData {
fn default() -> Self {
Self {
// Discord docs mention 45000 seconds - discord.sex mentions 41250. Defaulting to 45s
heartbeat_interval: 45000,
}
}
}
```
=> More accurate "GatewayHello::default()"

Cargo.lock, Cargo.toml, chorus-macros/src/lib.rs, src/types/config/types/guild_configuration.rs, src/types/entities/application.rs, src/types/entities/audit_log.rs, src/types/entities/channel.rs, src/types/entities/user.rs, src/types/utils/snowflake.rs
This PR bumps chorus from sqlx v0.7.4 to sqlx v0.8.0, which had some backwards incompatible changes. Also, instead of requiring MySQL/MariaDB to be used with chorus/sqlx, this PR enables any database driver to be used via the sqlx::Any Database Driver.
Closes #541 when merged.
=> sqlx related improvements

.github/workflows/cargo-doc.yml
Adds a `cargo doc` job to add rustdoc lints to code scanning, similar to clippy.
Note: under the hood, I literally used `clippy-sarif`; I haven't been able to find an equivalent for rustdoc, but it seems to work well
=> CI/CD: add cargo-doc job

.github/workflows/build_and_test.yml, Cargo.lock, Cargo.toml, chorus-macros/src/lib.rs, src/api/channels/messages.rs, src/lib.rs, src/types/config/types/guild_configuration.rs, src/types/entities/application.rs, src/types/entities/attachment.rs, src/types/entities/audit_log.rs, src/types/entities/auto_moderation.rs, src/types/entities/channel.rs, src/types/entities/emoji.rs, src/types/entities/guild.rs, src/types/entities/integration.rs, src/types/entities/invite.rs, src/types/entities/message.rs, src/types/entities/relationship.rs, src/types/entities/role.rs, src/types/entities/security_key.rs, src/types/entities/stage_instance.rs, src/types/entities/sticker.rs, src/types/entities/team.rs, src/types/entities/template.rs, src/types/entities/user.rs, src/types/entities/user_settings.rs, src/types/entities/webhook.rs, src/types/schema/channel.rs, src/types/utils/snowflake.rs
Initial support for using chorus with a PostgreSQL database, using the `backend` feature. In the same step, this removes support for MySQL/MariaDB. This does not mean that all types are now fully compatible with Postgres. Only the types needed in the current revision of symfonia have been ported over.
Interestingly, the `sqlx` docs mention the following when deriving `sqlx::Type` for structs in Postgres:
> ### Records
>
> User-defined composite types are supported through deriving a struct.
> 
> This is only supported for PostgreSQL.
> [ⓘ](https://docs.rs/sqlx/latest/sqlx/trait.Type.html#)
> 
> ```rs
> #[derive(sqlx::Type)]
> #[sqlx(type_name = "interface_type")]
> struct InterfaceType {
>     name: String,
>     supplier_id: i32,
>     price: f64
> }
> ```
=> Initial support for PostgreSQL

Cargo.lock, Cargo.toml, src/types/utils/snowflake.rs
For the implementation of the traits `sqlx::Type`, `sqlx::postgres::PgHasArrayType` and so on for our `Snowflake` type, `String` was used as an intermediary conversion target. This has worked so far, but with schemas/migrations changing in symfonia to more accurately represent the types of data being used, `String` is not a valid intermediary anymore. We use the `sqlx_pg_uint` crate and its `PgU64` type to convert from a PostgreSQL `NUMERIC` to a Rust `u64`. This pull request reflects this in our implementations of the sqlx traits.
=> Snowflake: PgU64 as base for sqlx

Cargo.lock, chorus-macros/Cargo.toml, chorus-macros/src/lib.rs
The same as #551, applied to the `sqlx_bitflag_derive` derive macro in the `chorus_macros` helper crate.
=> sqlx_bitflag_derive: Use PgU64 as translation base

examples/gateway_observers.rs, examples/gateway_simple.rs, src/api/auth/login.rs, src/api/auth/mod.rs, src/api/auth/register.rs, src/api/channels/messages.rs, src/gateway/gateway.rs, src/gateway/options.rs, src/instance.rs, src/lib.rs, src/types/utils/jwt.rs, src/voice/gateway/gateway.rs, src/voice/gateway/handle.rs, tests/auth.rs, tests/common/mod.rs, tests/gateway.rs
When I started Rust and didn't know lifetimes, I used `String` over `&str` everywhere, because it was easier to work with. This makes for very annoying API though. This PR changes `String` arguments in function headers to be `&str`, if possible. Should also make for some minor performance gains, even though this is not the goal
=> Prefer `&str` over `String` when possible

src/api/instance.rs, src/api/mod.rs, src/api/policies/instance/instance.rs, src/gateway/options.rs, src/instance.rs, src/types/schema/instance.rs, src/types/schema/mod.rs, tests/instance.rs
- Implements the `/ping` and `/version` endpoints
- Adds a software field to `Instance`, which is automatically determined
- If no specific `GatewayOptions` are provided, they will be automatically created based off the instance's software
- Adds a bit better error handling to /policies/instance, fixes a bug where it doesn't work on spacebar (missing a trailing slash)
=> Differentiate between instance softwares

src/types/config/types/subconfigs/defaults/user.rs
In `UserDefaults`, the field `premium_type` allowed for invalid values. This PR fixes this.
=> Adjust premium_type field to be of type PremiumType

src/types/entities/relationship.rs
As outlined in #565 and #566, some types in chorus are not yet ready for use in symfonia/sqlx. This PR fixes the Relationship struct RelationshipType enum.
=> Make Relationship struct sqlx/symfonia-ready

src/gateway/mod.rs, src/types/utils/mod.rs, src/types/utils/opcode.rs
Introduces and publicly exports an enum `Opcode` which represents all currently known Opcodes that can be sent to/received from Spacebar Gateway Protocol compatible services.
=> Add Gateway Opcode enum

src/types/utils/opcode.rs
This PR would add `VoiceCloseCode` and `CloseCode` to chorus with the ability to convert them from a tungstenite Message, and to a tungstenite CloseFrame.
=> Gateway disconnect opcodes

.github/workflows/build_and_test.yml, Cargo.lock, Cargo.toml, src/errors.rs, src/gateway/backends/tungstenite.rs, src/gateway/backends/wasm.rs, src/gateway/gateway.rs, src/gateway/message.rs, src/voice/gateway/backends/mod.rs, src/voice/gateway/backends/tungstenite.rs, src/voice/gateway/backends/wasm.rs, src/voice/gateway/gateway.rs, src/voice/gateway/message.rs, tests/gateway.rs
also introduces a test for receiving the close codes. 
Differentiates the wasm and tungstenite gateways a bit more.
The same thing should be done for the voice gateway, I'll likely add it to this pr if the mod to the normal gateway is okay
=> Refactor the gateway to properly accept close frames

src/gateway/events.rs, src/gateway/gateway.rs, src/gateway/handle.rs, src/gateway/heartbeat.rs, src/gateway/mod.rs, src/types/entities/relationship.rs, src/types/events/call.rs, src/types/events/guild.rs, src/types/events/lazy_request.rs, src/types/events/message.rs, src/types/events/presence.rs, src/types/events/ready.rs, src/types/events/request_members.rs, src/types/utils/mod.rs, src/types/utils/snowflake.rs
See the commits; 
- Discord is messing with their api again, read states are a mystery
- Refactored the gateway to fully use the `Opcode` enum instead of constants (4ed68ce7a506d0354730b4b4f0b7d4267c5e2a50)
- Added Last Messages request and response (4ed68ce7a506d0354730b4b4f0b7d4267c5e2a50)
- Fixed a deserialization error related to `presences` in `GuildMembersChunk` being an array, not a single value (4baecf978415b680d5ef13061c24e5e363d19988)
- Fixed a deserialization error with deserializing `activities` in `PresenceUpdate` as an empty array when they are sent as `null` (1b201020e9dec23e2dfcd467e49c58b151d88e0e)
- Add type `OneOrMoreSnowflakes`, allow `GatewayRequestGuildMembers` to request multiple guild and user ids (644d3beb90bc1aedd2dd222cab199457d4dffddd, …
=> Fix some gateway deserialization errors

Cargo.toml
Fix pharos being a wildcard dependency, to be able to publish to crates.
My bad here
=> fix: wildcard dependency

Cargo.lock, Cargo.toml, src/gateway/backends/tungstenite.rs, src/gateway/message.rs, src/voice/gateway/backends/tungstenite.rs
This reverts commit 64d723fc9c81c588bde8d0f0226172b248e33cd5.
Because dependabot targets main
=> Revert "Bump rustls to 0.23.20 and tokio_tungstenite to 0.26.1 (#583)"

src/api/auth/login.rs, src/api/auth/mod.rs, src/api/auth/register.rs, src/api/channels/channels.rs, src/api/channels/messages.rs, src/api/channels/permissions.rs, src/api/channels/reactions.rs, src/api/guilds/guilds.rs, src/api/guilds/member.rs, src/api/guilds/roles.rs, src/api/invites/mod.rs, src/api/users/channels.rs, src/api/users/connections.rs, src/api/users/guilds.rs, src/api/users/mfa.rs, src/api/users/relationships.rs, src/api/users/users.rs, src/instance.rs, src/ratelimiter.rs, src/types/events/identify.rs, src/types/interfaces/client_properties.rs, src/types/interfaces/mod.rs, tests/common/mod.rs
Implements a new approach to client properties from #584 
Each `ChorusUser` now has its own `ClientProperties` struct, which contains telemetry data sent when identifying with the gateway and with every request to the HTTP API. 
This also means every request includes three new headers: `X-Super-Properties` (the entire `ClientProperties` encoded in base 64), `X-Discord-Locale` (which is copied from `ClientProperties.system_locale`) and `X-Debug-Options` (which is set to a hard-coded value of `bugReporterEnabled`)
Internally this also removes the old api `ChorusRequest::new` in favor of `ChorusRequest {}`, along with refactoring how headers are set on all routes
=> Client properties API

src/errors.rs, src/gateway/events.rs, src/gateway/gateway.rs, src/gateway/handle.rs, src/gateway/mod.rs, src/gateway/observers.rs, src/types/events/request_members.rs, src/types/events/resume.rs, tests/gateway.rs
Adds some new methods to `GatewayHandle`:
- `identify`, which functions like `send_identify`, but waits to receive the response
- `resume`, which functions like `send_resume`, but waits to receive the response
- `request_guild_members`, which functions like `send_request_guild_members`, but waits to receive all `GuildMembersChunk`s
- `update_voice_state`, which functions like `send_update_voice_state`, but waits up to 1 second to receive a potential response
- `request_last_messages`, which functions like `send_request_last_messages`, but waits to receive the response
These work by creating a temporary observer, which sends the event through either a `tokio::sync::broadcast` or `tokio::sync::oneshot` channel. These two observer types are now also part of the public api as …
=> Add api for awaiting responses to gateway send events

src/types/entities/user_settings.rs
According to the trusty <https://docs.discord.sex/resources/presence#status-type>, a UserStatus enum variant was missing.
=> Add UserStatus variant "Unknown"

src/types/interfaces/client_properties.rs
=> Skip send_telemetry_headers when deserializing ClientProperties

src/gateway/events.rs, src/instance.rs, src/types/config/types/guild_configuration.rs, src/types/events/passive_update.rs
- add field `default_gateway_events` to `Instance`, which allows users to subscribe observers that are duplicated on every new gateway connection created by the instance. This allows users to subscribe to events such as `Ready`, which are received before an observer can be created. Another potential use-case would be to create observers that are used and called for all gateway connections.
- makes gateway `Events` clonable
=> Instance default events API

src/api/users/relationships.rs, src/types/entities/relationship.rs, src/types/schema/relationship.rs
Note `user_ignored` does not exist on Spacebar; I think we can just default it to `false` if it does not exist
closes #601 
also: this breaks the symfonia relationship create migration
=> Add user ignore api, update relationship entity

README.md, examples/instance.rs, examples/login.rs, src/api/auth/login.rs, src/api/auth/mod.rs, src/api/auth/register.rs, src/lib.rs, src/types/mod.rs, tests/auth.rs, tests/common/mod.rs, tests/instance.rs
This is a pretty old bug (#133) that I don't know why we / I didn't fix earlier
Makes the code reuse `Instance` references, requiring them to be passed in auth methods.
As such the examples and tests were also updated to make the best-practice saving `Instance` under `Shared<Instance>`
Also fixes the `send_mfa_sms` method to use anonymous requests instead of cloning the instance with `ChorusUser::shell`
=> Fix cloning of instances

README.md, examples/instance.rs, examples/login.rs, src/api/auth/login.rs, src/api/auth/register.rs, src/api/instance.rs, src/api/policies/instance/instance.rs, src/gateway/events.rs, src/instance.rs, src/lib.rs, src/ratelimiter.rs, src/types/entities/ratelimits.rs, tests/common/mod.rs
Adds a builder pattern for `Instance` - `InstanceBuilder` - which can be used to more precisely specify options before creating the `Instance`.
Adds the options to:
- disable automatically detecting the software with `with_software`,
- specify gateway options with `with_gateway_options`,
- add default event observers with `.default_gateway_events`,
- set default telemetry data (and telemetry sent in instance requests) with `with_client_properties` and
- skip optional requests which may reveal we are using chorus (see #584) with `skip_fetching_ratelimits`, `skip_fetching_general_info` & `skip_optional_requests`
Replaces `Instance::from_url_bundle` with `InstanceBuilder::build` as the main Instance initialization method
Changes `Instance::from_url_bundle` and `Instance::new` to no longer …
=> Add builder pattern for Instance
